services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || true &&
      gunicorn backend.wsgi
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        value: elton pogi
      - key: DJANGO_SUPERUSER_EMAIL
        value: elton@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Elton@123
      