# Generated by Django 5.1.6 on 2025-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('love', '❤️ Love')], max_length=10),
        ),
    ]
